title: Twileloop.EntraWrapper
description: "Helps configuring AzureAD B2C by simplifying integration and giving a ready to use template"
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
  zip_url: https://github.com/sangeethnandakumar/Twileloop.EntraWrapper/releases
  tar_url: https://www.nuget.org/packages/Twileloop.EntraWrapper
